### ISSUE TITLE
set up environment

### ISSUE THREAD

**Issue by cassianobecker** [cassianobecker/dnn#1]
conda env

**Comment by cassianobecker** [comment]
Closed issue #3 (please see comments on dependencies)

**Comment by cassianobecker** [comment]
As an IDE, I recommend PyCharm.
For now, community edition suffices: https://www.jetbrains.com/pycharm/download/#section=mac

**Comment by harangju** [comment]
See README for how to set up environment for either command line or PyCharm.
Also created gitignore file.
